"""initial tables with auth_key_hash as string

Revision ID: 63ee154adec0
Revises: 
Create Date: 2026-04-04 02:22:32.939956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63ee154adec0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'auth_key_hash',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'auth_key_hash',
               existing_type=sa.String(length=255),
               type_=postgresql.BYTEA(),
               existing_nullable=False)
    # ### end Alembic commands ###
